### ISSUE TITLE
Blackmagic drivers cannot be installed on windows

### ISSUE THREAD

**Issue by stevegtaylor** [jlab-sensing/soil-power-sensor-firmware#19]
There is no manufacturer signature on the blackmagic drivers. So windows throws `The third-party INF does not contain digital signaturers`. Windows machines cannot communicate over the blackmagic COM ports until this is resolved.

**Comment by jmadden173** [comment]
Closing this issue as it appears to be with the bmp itself and the st-link has the same functionality as bmp since #1
